# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on: push

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodule
      run: git submodule update --init --recursive
    - name: pybind11
      run: |
        git submodule add -b stable ../../pybind/pybind11 contrib/pybind11
        git submodule update --init
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    #- name: Login do docker.io
    #  run: docker login -u abhishek138 -p abhishek138
    #- name: build and publish image
    #  id: docker_build
    #  uses: docker/build-push-action@v2
    #  with:
    #      context: .
    #      file: ./Dockerfile
    #      platforms: linux/amd64
    #      push: true
    #      tags: |
    #        abhishek138/api:latest
    - name: Build cpp
      run: |
        git clone https://github.com/dolphindb/api-cplusplus
        cd api-cplusplus
        g++ main.cpp -std=c++11 -DLINUX -D_GLIBCXX_USE_CXX11_ABI=0 -DLOGGING_LEVEL_2 -O2 -I../include   -lDolphinDBAPI -lpthread -lssl -L../bin/linux_x64/ABI0  -Wl,-rpath,.:../bin/linux_x64/ABI0 -o main
    - name: Build package
      run: |
        chmod 777 ./build.sh
        chmod 777 ./build-wheels.sh
        ./build.sh
